//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.13

pub use super::access_tokens::Entity as AccessTokens;
pub use super::authorization_codes::Entity as AuthorizationCodes;
pub use super::o_auth_clients::Entity as OAuthClients;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::users::Entity as Users;
