//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub role: String,
    pub is_active: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub login_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_tokens::Entity")]
    AccessTokens,
    #[sea_orm(has_many = "super::app_settings::Entity")]
    AppSettings,
    #[sea_orm(has_many = "super::authorization_codes::Entity")]
    AuthorizationCodes,
    #[sea_orm(has_many = "super::config_audit_logs::Entity")]
    ConfigAuditLogs,
}

impl Related<super::access_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessTokens.def()
    }
}

impl Related<super::app_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppSettings.def()
    }
}

impl Related<super::authorization_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorizationCodes.def()
    }
}

impl Related<super::config_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigAuditLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
